### PR TITLE
US6466 typography settings

### PR DESCRIPTION
**Pull request by nogorilla**
@zarahzachz Do you mind looking over this. Looks like `.page-header`, `.section-header`, `.title`,`.collection-header`, `.card-title`, and `.list-header` will be under "Headings" section and the other listed styles will be under the "Typesetting" section. It might be necessary to consolidate those sections.

### CODE REVIEW

**Comment by nogorilla** [comment]
Feedback from Sarah:

- [ ] Revert headings section to show exact sizing of header elements.
- [ ] changed "Headings" to "Font Scale"
  - [ ] apply sass variable font sizes to `crds-styles` and apply to each header element. see typefaces for both variable and class applications
- [ ] add the semantic font descriptions currently on header section to typesetting section.

**Comment by nogorilla** [comment]
@zarahzachz Updated "Heading" section to "Font Scaling" and restore `h1`-`h6` elements, included font-size classes description, and other font-size classes. Typesetting now contains the semantic header classes.

Sibling PR: https://github.com/crdschurch/crds-styles/tree/feature/US6466-typography-settings

**Comment by zarahzachz** [comment]
This looks good, but there are styles in this repo overriding header styles in `crds-styles`. This should be resolved by removing lines 52-64 from https://github.com/crdschurch/crds-styleguide/blob/development/src/styles/_global.scss#L52

**Comment by nogorilla** [comment]
@zarahzachz thanks. Its ready to merge.

**Comment by tcmacdonald** [comment]
@nogorilla @zarahzachz – This has some problems. Lets chat in the morning. 

crds_styleguide

**Comment by nogorilla** [comment]
@tcmacdonald did you pull the latest? I updated so that the styleguide wouldn't override values set in `crds-styles`

crds_styleguide

**Pull request merged**
